// Generated by NLWebAgent - login-test.spec.ts
// This is an example of the Playwright code generated from a recorded session
import { test, expect } from '@playwright/test';

test('login shows dashboard', async ({ page }) => {
  // Navigate to login page
  await page.goto('https://example.com/login');

  // Fill credentials
  await page.fill('#email', 'test@example.com');
  await page.fill('#password', 'your-password');

  // Submit form
  await page.click('button[type="submit"]');

  // Verify dashboard loaded
  await expect(page.locator('h1.dashboard-title')).toContainText('Welcome Back');

  // Suggestion: Add assertion for user avatar visibility
  // await expect(page.locator('.user-avatar')).toBeVisible();
});
