"""
Playwright test code generator.

Converts recorded browser sessions into Playwright TypeScript test code.
"""
import re
from typing import Dict, List, Optional, Any
from datetime import datetime


def generate_playwright_test(
    recording: Dict[str, Any],
    test_name: str = "test_recorded",
    add_assertions: bool = True,
) -> str:
    """
    Generate a Playwright TypeScript test from a recording.

    Args:
        recording: Dict containing url, actions, extractions, etc.
        test_name: Name for the generated test function
        add_assertions: Whether to add assertion suggestions

    Returns:
        Generated TypeScript test code as string
    """
    url = recording.get("url", "")
    actions = recording.get("actions", [])
    extractions = recording.get("extractions", [])
    transcript = recording.get("transcript", [])

    lines = [
        "// Generated by NLWebAgent",
        f"// Generated: {datetime.now().isoformat()}",
        f"// URL: {url}",
        "",
        "import { test, expect } from '@playwright/test';",
        "",
        f"test('{test_name}', async ({{ page }}) => {{",
    ]

    # Navigate to starting URL
    lines.append(f"  await page.goto('{url}');")

    # Process each action
    for i, action in enumerate(actions):
        action_str = action.get("action", "")
        playwright_action = _convert_action_to_playwright(action_str, i)

        if playwright_action:
            lines.append(f"  {playwright_action}")

    # Add assertion suggestions
    if add_assertions and extractions:
        lines.append("")
        lines.append("  // Assertion suggestions based on recorded extractions:")
        for ext in extractions:
            selector = ext.get("selector", "")
            value = ext.get("value", "")
            if selector and value:
                # Escape quotes in value
                value_escaped = str(value).replace("'", "\\'")[:50]
                lines.append(
                    f"  // await expect(page.locator('{selector}')).toContainText('{value_escaped}');"
                )

    # Add common assertions
    if add_assertions:
        lines.append("")
        lines.append("  // Verify page loaded")
        lines.append("  await expect(page).toHaveURL(/.*\\.*/);")

    lines.append("});")
    lines.append("")

    return "\n".join(lines)


def _convert_action_to_playwright(action: str, index: int) -> Optional[str]:
    """
    Convert a recorded action string to Playwright TypeScript code.

    Args:
        action: Action string like "CLICK:#button" or "TYPE:#input:hello"
        index: Action index for comments

    Returns:
        Playwright TypeScript code or None if not convertible
    """
    if not action:
        return None

    action = action.strip()
    upper = action.upper()

    # Parse action type and parameters
    if upper.startswith("CLICK:"):
        selector = action.split(":", 1)[1] if ":" in action else ""
        if selector:
            return f"await page.click('{_escape_selector(selector)}');  // Step {index + 1}"

    elif upper.startswith("CLICK_AT:"):
        parts = action.split(":")
        if len(parts) >= 3:
            x, y = parts[1], parts[2]
            return f"await page.mouse.click({x}, {y});  // Step {index + 1}"

    elif upper.startswith("TYPE:"):
        parts = action.split(":", 2)
        if len(parts) >= 3:
            selector, text = parts[1], parts[2]
            text_escaped = _escape_string(text)
            return (
                f"await page.fill('{_escape_selector(selector)}', '{text_escaped}');"
                f"  // Step {index + 1}"
            )

    elif upper.startswith("TYPE_AT:"):
        parts = action.split(":", 3)
        if len(parts) >= 4:
            x, y, text = parts[1], parts[2], parts[3]
            text_escaped = _escape_string(text)
            return (
                f"await page.mouse.click({x}, {y}); "
                f"await page.keyboard.type('{text_escaped}');  // Step {index + 1}"
            )

    elif upper.startswith("NAVIGATE:"):
        url = action.split(":", 1)[1] if ":" in action else ""
        if url:
            return f"await page.goto('{url}');  // Step {index + 1}"

    elif upper.startswith("SCROLL:"):
        parts = action.split(":", 2)
        if len(parts) >= 3:
            direction, amount = parts[1].lower(), parts[2]
            if direction == "down":
                return f"await page.evaluate('window.scrollBy(0, {amount})');  // Step {index + 1}"
            elif direction == "up":
                return f"await page.evaluate('window.scrollBy(0, -{amount})');  // Step {index + 1}"

    elif upper.startswith("WAIT:"):
        seconds = action.split(":", 1)[1] if ":" in action else "1"
        try:
            ms = int(float(seconds) * 1000)
            return f"await page.waitForTimeout({ms});  // Step {index + 1}"
        except ValueError:
            return None

    elif upper.startswith("EXTRACT:"):
        parts = action.split(":", 2)
        if len(parts) >= 3:
            selector, attr = parts[1], parts[2]
            return f"const value{index} = await page.locator('{_escape_selector(selector)}').textContent();  // Step {index + 1}"

    elif upper == "DONE":
        return "// Task completed"

    # Unknown action - add as comment
    return f"// TODO: {action}"


def _escape_selector(selector: str) -> str:
    """Escape a CSS selector for use in a string literal."""
    # Basic escaping - just handle quotes
    return selector.replace("'", "\\'").replace('"', '\\"')


def _escape_string(text: str) -> str:
    """Escape a text string for use in a string literal."""
    return text.replace("'", "\\'").replace('"', '\\"').replace("\n", "\\n")


def generate_test_from_transcript(
    transcript: List[Dict],
    url: str,
    test_name: str = "test_from_transcript",
) -> str:
    """
    Generate a Playwright test from a browser transcript.

    Args:
        transcript: List of transcript entries from BrowserController
        url: Starting URL
        test_name: Name for the generated test

    Returns:
        Generated TypeScript test code
    """
    actions = []

    for entry in transcript:
        action_type = entry.get("action", "")

        if action_type == "navigate":
            actions.append({"action": f"NAVIGATE:{entry.get('url', '')}"})

        elif action_type == "click":
            actions.append({"action": f"CLICK:{entry.get('selector', '')}"})

        elif action_type == "type":
            # Note: transcript doesn't store the typed text, so we use placeholder
            actions.append({"action": f"TYPE:{entry.get('selector', '')}:<typed_text>"})

        elif action_type == "click_at":
            x, y = entry.get("x", 0), entry.get("y", 0)
            actions.append({"action": f"CLICK_AT:{x}:{y}"})

        elif action_type == "type_at":
            x, y = entry.get("x", 0), entry.get("y", 0)
            actions.append({"action": f"TYPE_AT:{x}:{y}:<typed_text>"})

        elif action_type == "extract":
            actions.append({
                "action": f"EXTRACT:{entry.get('selector', '')}:{entry.get('attr', 'text')}"
            })

    return generate_playwright_test(
        recording={"url": url, "actions": actions},
        test_name=test_name,
    )
